// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeuGerente.Infrastructure.Persistence;

#nullable disable

namespace SeuGerente.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507014419_AddEvolutionTokenColumns")]
    partial class AddEvolutionTokenColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeuGerente.Domain.Entities.Administrativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("administrativo", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Assinatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CadastroId")
                        .HasColumnType("uuid")
                        .HasColumnName("cadastro_id");

                    b.Property<string>("ClienteEmail")
                        .HasColumnType("text")
                        .HasColumnName("cliente_email");

                    b.Property<string>("ClienteNome")
                        .HasColumnType("text")
                        .HasColumnName("cliente_nome");

                    b.Property<string>("ClienteWhatsapp")
                        .HasColumnType("text")
                        .HasColumnName("cliente_whatsapp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cancelamento");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<int?>("DiasAtraso")
                        .HasColumnType("integer")
                        .HasColumnName("dias_atraso");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("MotivosCancelamento")
                        .HasColumnType("text")
                        .HasColumnName("motivos_cancelamento");

                    b.Property<string>("NomeCondominio")
                        .HasColumnType("text")
                        .HasColumnName("nome_condominio");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plano");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StatusPagamento")
                        .HasColumnType("text")
                        .HasColumnName("status_pagamento");

                    b.Property<DateTime?>("UltimaNotificacaoAtraso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_notificacao_atraso");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.Property<decimal?>("ValorPago")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("Status");

                    b.ToTable("assinaturas", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Banner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imagem_url");

                    b.Property<string>("ObjectPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_path");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id");

                    b.ToTable("banners", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Cadastro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CnpjCpf")
                        .HasColumnType("text")
                        .HasColumnName("cnpj_cpf");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmado");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeCondominio")
                        .HasColumnType("text")
                        .HasColumnName("nome_condominio");

                    b.Property<int?>("QuantidadeApartamentos")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_apartamentos");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TokenConfirmacaoEmail")
                        .HasColumnType("text")
                        .HasColumnName("token_confirmacao_email");

                    b.Property<DateTime?>("TokenConfirmacaoExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_confirmacao_expira_em");

                    b.Property<string>("TokenResetSenha")
                        .HasColumnType("text")
                        .HasColumnName("token_reset_senha");

                    b.Property<DateTime?>("TokenResetSenhaExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_reset_senha_expira_em");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("cadastro", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Configuracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int?>("DiaEnvioCobranca")
                        .HasColumnType("integer")
                        .HasColumnName("dia_envio_cobranca");

                    b.Property<int?>("DiaEnvioRelatorio")
                        .HasColumnType("integer")
                        .HasColumnName("dia_envio_relatorio");

                    b.Property<int?>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool?>("EnvioAutomaticoAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("envio_automatico_ativo");

                    b.Property<TimeSpan?>("HoraEnvioCobranca")
                        .HasColumnType("interval")
                        .HasColumnName("hora_envio_cobranca");

                    b.Property<TimeSpan?>("HoraEnvioRelatorio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_envio_relatorio");

                    b.Property<string>("MensagemCobranca")
                        .HasColumnType("text")
                        .HasColumnName("mensagem_cobranca");

                    b.Property<string>("MensagemRelatorio")
                        .HasColumnType("text")
                        .HasColumnName("mensagem_relatorio");

                    b.Property<string>("MesReferenciaCobranca")
                        .HasColumnType("text")
                        .HasColumnName("mes_referencia_cobranca");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("PixCobranca")
                        .HasColumnType("text")
                        .HasColumnName("pix_cobranca");

                    b.Property<string>("PixNomeBeneficiario")
                        .HasColumnType("text")
                        .HasColumnName("pix_nome_beneficiario");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("configuracao", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.ConfiguracaoEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("EmailRemetente")
                        .HasColumnType("text")
                        .HasColumnName("email_remetente");

                    b.Property<string>("SenhaApp")
                        .HasColumnType("text")
                        .HasColumnName("senha_app");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("configuracao_email", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.ConfiguracaoSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chave");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Valor")
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("configuracao_sistema", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("ComprovanteUrl")
                        .HasColumnType("text")
                        .HasColumnName("comprovanteurl");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Enviado")
                        .HasColumnType("text")
                        .HasColumnName("enviado");

                    b.Property<Guid?>("MelhoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("melhoria_id");

                    b.Property<string>("MelhoriaTitulo")
                        .HasColumnType("text")
                        .HasColumnName("melhoria_titulo");

                    b.Property<string>("Origem")
                        .HasColumnType("text")
                        .HasColumnName("origem");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TipoDivisao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_divisao");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.Property<decimal[]>("ValoresPorAp")
                        .HasColumnType("numeric[]")
                        .HasColumnName("valoresporap");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("despesas", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.DespesaSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_lancamento");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pendente")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Status");

                    b.ToTable("despesas_sistema", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.LogSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text")
                        .HasColumnName("detalhes");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivel");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("Nivel");

                    b.HasIndex("UsuarioId");

                    b.ToTable("logs_sistema", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Melhoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CustoEstimado")
                        .HasColumnType("numeric")
                        .HasColumnName("custo_estimado");

                    b.Property<decimal?>("CustoReal")
                        .HasColumnType("numeric")
                        .HasColumnName("custo_real");

                    b.Property<DateTime?>("DataFimPrevista")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim_prevista");

                    b.Property<DateTime?>("DataFimReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim_real");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prioridade");

                    b.Property<string>("Responsavel")
                        .HasColumnType("text")
                        .HasColumnName("responsavel");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("melhorias", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Morador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("moradores", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Caixinha")
                        .HasColumnType("numeric")
                        .HasColumnName("caixinha");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("MesAno")
                        .HasColumnType("text")
                        .HasColumnName("mes_ano");

                    b.Property<string>("MoradorEmail")
                        .HasColumnType("text")
                        .HasColumnName("morador_email");

                    b.Property<Guid?>("MoradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("morador_id");

                    b.Property<string>("MoradorNome")
                        .HasColumnType("text")
                        .HasColumnName("morador_nome");

                    b.Property<string>("MoradorNumero")
                        .HasColumnType("text")
                        .HasColumnName("morador_numero");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UrlComprovante")
                        .HasColumnType("text")
                        .HasColumnName("url_comprovante");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("MesAno");

                    b.HasIndex("MoradorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("pagamentos", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("receitas", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataReserva")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_reserva");

                    b.Property<string>("Espaco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("espaco");

                    b.Property<string>("HoraFim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hora_fim");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Morador")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("morador");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("reservas", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Sugestao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sugestoes", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.WhatsAppInstancia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EvolutionInstanceId")
                        .HasColumnType("text")
                        .HasColumnName("evolution_instance_id");

                    b.Property<string>("EvolutionToken")
                        .HasColumnType("text")
                        .HasColumnName("evolution_token");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instance_name");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("InstanceName")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("whatsapp_instancias", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Assinatura", b =>
                {
                    b.HasOne("SeuGerente.Domain.Entities.Cadastro", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadastro");
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("SeuGerente.Domain.Entities.Morador", "Morador")
                        .WithMany("Pagamentos")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Morador");
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Morador", b =>
                {
                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
