// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeuGerente.Infrastructure.Persistence;

#nullable disable

namespace SeuGerente.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260222180633_AddPixNomeBeneficiarioToConfiguracao")]
    partial class AddPixNomeBeneficiarioToConfiguracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeuGerente.Domain.Entities.Cadastro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CnpjCpf")
                        .HasColumnType("text")
                        .HasColumnName("cnpj_cpf");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("MercadopagoPaymentId")
                        .HasColumnType("text")
                        .HasColumnName("mercadopago_payment_id");

                    b.Property<string>("MercadopagoPreferenceId")
                        .HasColumnType("text")
                        .HasColumnName("mercadopago_preference_id");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeCondominio")
                        .HasColumnType("text")
                        .HasColumnName("nome_condominio");

                    b.Property<int?>("QuantidadeApartamentos")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_apartamentos");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("cadastro", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Configuracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int?>("DiaEnvioCobranca")
                        .HasColumnType("integer")
                        .HasColumnName("dia_envio_cobranca");

                    b.Property<int?>("DiaEnvioRelatorio")
                        .HasColumnType("integer")
                        .HasColumnName("dia_envio_relatorio");

                    b.Property<int?>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool?>("EnvioAutomaticoAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("envio_automatico_ativo");

                    b.Property<TimeSpan?>("HoraEnvioCobranca")
                        .HasColumnType("interval")
                        .HasColumnName("hora_envio_cobranca");

                    b.Property<TimeSpan?>("HoraEnvioRelatorio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_envio_relatorio");

                    b.Property<string>("MensagemCobranca")
                        .HasColumnType("text")
                        .HasColumnName("mensagem_cobranca");

                    b.Property<string>("MensagemRelatorio")
                        .HasColumnType("text")
                        .HasColumnName("mensagem_relatorio");

                    b.Property<string>("MesReferenciaCobranca")
                        .HasColumnType("text")
                        .HasColumnName("mes_referencia_cobranca");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("PixCobranca")
                        .HasColumnType("text")
                        .HasColumnName("pix_cobranca");

                    b.Property<string>("PixNomeBeneficiario")
                        .HasColumnType("text")
                        .HasColumnName("pix_nome_beneficiario");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("configuracao", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.ConfiguracaoEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("EmailRemetente")
                        .HasColumnType("text")
                        .HasColumnName("email_remetente");

                    b.Property<string>("SenhaApp")
                        .HasColumnType("text")
                        .HasColumnName("senha_app");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("configuracao_email", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("ComprovanteUrl")
                        .HasColumnType("text")
                        .HasColumnName("comprovanteurl");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Enviado")
                        .HasColumnType("text")
                        .HasColumnName("enviado");

                    b.Property<Guid?>("MelhoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("melhoria_id");

                    b.Property<string>("Origem")
                        .HasColumnType("text")
                        .HasColumnName("origem");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TipoDivisao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_divisao");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.Property<decimal[]>("ValoresPorAp")
                        .HasColumnType("numeric[]")
                        .HasColumnName("valoresporap");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("despesas", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Melhoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CustoEstimado")
                        .HasColumnType("numeric")
                        .HasColumnName("custo_estimado");

                    b.Property<decimal?>("CustoReal")
                        .HasColumnType("numeric")
                        .HasColumnName("custo_real");

                    b.Property<DateTime?>("DataFimPrevista")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim_prevista");

                    b.Property<DateTime?>("DataFimReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim_real");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prioridade");

                    b.Property<string>("Responsavel")
                        .HasColumnType("text")
                        .HasColumnName("responsavel");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("melhorias", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Morador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("moradores", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Caixinha")
                        .HasColumnType("numeric")
                        .HasColumnName("caixinha");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("MercadoPagoId")
                        .HasColumnType("text")
                        .HasColumnName("mercado_pago_id");

                    b.Property<string>("MesAno")
                        .HasColumnType("text")
                        .HasColumnName("mes_ano");

                    b.Property<Guid?>("MoradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("morador_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UrlComprovante")
                        .HasColumnType("text")
                        .HasColumnName("url_comprovante");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("MesAno");

                    b.HasIndex("MoradorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("pagamentos", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("receitas", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Sugestao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sugestoes", (string)null);
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("SeuGerente.Domain.Entities.Morador", "Morador")
                        .WithMany("Pagamentos")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Morador");
                });

            modelBuilder.Entity("SeuGerente.Domain.Entities.Morador", b =>
                {
                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
